# Inverse Matriser (MIP 10.7)

De kvadratiske matrisene

$$
\left[\begin{array}{cc}
1 & 0 \\
0 & 1
\end{array}\right],
\quad
\left[\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right],
\quad
\text{osv}
$$


er spesielle: Ganges de på en annen matrise $A$ blir resultatet matrisen $A$ selv. 

## Eksempel

$$
\left[\begin{array}{cc}
1 & 0 \\ 0 & 1
\end{array}\right]
\cdot
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
=
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
$$
og
$$
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
\cdot
\left[\begin{array}{cc}
1 & 0 \\ 0 & 1
\end{array}\right]
=
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
$$


## Oppgave

La $I$ være $3 \times 3$ matrisen
$$
I = 
\left[\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right]
$$
La $A$, $B$ og $C$ være $3 \times 3$ matriser slik at 
$$A \cdot B = I \quad \text{og} \quad B \cdot C = I.$$
Bruk regnereglene 
* $C = I \cdot C$,
* $(A \cdot B) \cdot C = A \cdot (B \cdot C)$
* $A \cdot I = A$

til å forklare hvorfor $C = A$.

## Invers matrise

I situasjonen i oppgaven over sier vi at $B$ er den inverse matrisen til $A$, og vi skriver
$$B = A^{-1}$$

### Bemerkning

Vi blir fortalt at $\det(A \cdot B) = \det(A) \cdot \det(B)$. Dessuten er det ikke vanskelig å sjekke at $\det(I) = 1$. Derfor vet vi at hvis $A \cdot B = I$, da er $\det(A) \cdot \det(B) = 1$, 
så vi vet både at $\det(A) \ne 0$ og at $\det(B) \ne 0$.

## Teorem

Hvis $\det(A) \ne 0$ da har $A$ en invers matrise.

### Begrunnelse:

La oss si at $A$ er en $3 \times 3$ matrise. Siden $\det(A) \ne 0$ ved vi fra Teorem 4 i avsnitt 10.4 i MIP at det 
finnes nøyaktig en løsning 
$$\vec b_1 = 
\left[\begin{array}{c}
b_{11} \\ b_{21} \\ b_{31}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_1 =
\left[\begin{array}{c}
1 \\ 0 \\ 0
\end{array}\right].$$
Tilsvarende
finnes nøyaktig en løsning 
$$\vec b_2 = 
\left[\begin{array}{c}
b_{12} \\ b_{22} \\ b_{32}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_2 =
\left[\begin{array}{c}
0 \\ 1 \\ 0
\end{array}\right].$$
Endelig finnes også nøyaktig en løsning 
$$\vec b_3 = 
\left[\begin{array}{c}
b_{13} \\ b_{23} \\ b_{33}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_3 =
\left[\begin{array}{c}
0 \\ 0 \\ 1
\end{array}\right].$$


Matrisen
$$
B = [\vec b_1\ \vec b_2 \ \vec b_3] = 
\left[\begin{array}{ccc}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\
b_{31} & b_{32} & b_{33}
\end{array}\right]$$

er slik at $A \cdot B = I$. (Hvorfor?) Vi vet nå fra bemerkningen over at $\det(B) \ne 0$, så på samme måte kan vi finne en matrise $C$ slik at $B \cdot C = I$.
Fra oppgaven over vet vi at $A = C$, så $B = A^{-1}$.

## Eksempel

$$A =
\left[\begin{array}{ccc}
1 & 1 & 0 \\
0 & 2 & 0 \\
0 & 1 & 1
\end{array}\right]$$

For å finne $\vec b_1$ gjør vi Gauss eliminasjon:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 1\\
0 & 2 & 0 & 0\\
0 & 1 & 1 & 0
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 1 & 1 & 0
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


som gir
$\vec b_1 = 
\left[\begin{array}{c}
1 \\ 0 \\0
\end{array}\right]$

For å finne $\vec b_2$ gjør vi igjen Gauss eliminasjon:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 2 & 0 & 1\\
0 & 1 & 1 & 0
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 1 & 0 & 1/2\\
0 & 1 & 1 & 0
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & -1/2\\
0 & 1 & 0 & 1/2\\
0 & 0 & 1 & -1/2
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


som gir
$\vec b_2 = 
\left[\begin{array}{c}
-1/2 \\ 1/2 \\ -1/2
\end{array}\right]$

På helt samme måte fås $\vec b_3 = 
\left[\begin{array}{c}
0 \\ 0 \\ 1
\end{array}\right]$:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 1 & 1 & 1
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 1 & 1 & 1
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -1
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


Den inverse matrisen til $A$ er altså

$$A^{-1} = 
\left[\begin{array}{ccc}
1 & -1/2 & 0 \\
0 & 1/2 & 0 \\
0 & -1/2 & 1
\end{array}\right]$$

## Forenkling

Vi kan gjøre alle Gauss eliminasjonene samtidig ved å jobbe med en større matrise:

$$
\left[\begin{array}{ccc|ccc}
1 & 1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 0 & 1 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
\sim
\left[\begin{array}{ccc|ccc}
1 & 1 & 0 & 0 & 1 & 0\\
0 & 1 & 0 & 0 & 1/2 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & -1/2 & 0\\
0 & 1 & 0 & 0 & 1/2 & 0\\
0 & 0 & 1 & 0 & -1/2 & 1
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


## Beregning av invers ved hjelp av python

Vi har allerede sett en python funksjon som kan gjøre Gauss Jordan eliminasjon. Denne funksjonen kan regne ut inverse matriser for oss.

In [1]:
import numpy as np

In [2]:
# importering av kode for gauss_jordan reduksjon
try:
    import python_linear_algebra as pla
except:
    !pip install python_linear_algebra@git+https://github.com/mbr085/python_linear_algebra
    import python_linear_algebra as pla
from python_linear_algebra.matrix_reduction import gauss_jordan, invers_matrise

Vi skriver matrisen fra før inn i python som en numpy array.

$$
AI = \left[\begin{array}{cccccc}
1 & 1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 0 & 1 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
$$


In [3]:
AI = np.array([
    [1, 1, 0, 1, 0, 0],
    [0, 2, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 1]
])

In [4]:
gauss_jordan(AI)

array([[ 2,  0,  0,  2, -1,  0],
       [ 0,  2,  0,  0,  1,  0],
       [ 0,  0,  2,  0, -1,  2]])

Her kan vi igjen lese av den inverse matrisen til $A$ fra høyre halvden av denne matrisen.

## Funksjon som regner ut invers matrise

Vi leste av den inverse matrisen til en matrise $A$ fra Gauss Jordan eliminasjonen av $A$. I stedet for skrive av resultatet for hånd kan vi lage en 
python funksjon som finner den inverse matrisen for oss.

In [5]:
A = np.array([
    [1, 1, 0],
    [0, 2, 0],
    [0, 1, 1]
])

In [6]:
invers_matrise(A)

/home/mbr085/projects/V26MAT102/.venv/lib/python3.12/site-packages/python_linear_algebra/matrix_reduction.py:268: UserWarning: Matrisen A har ikke en heltallig invers.
  warnings.warn("Matrisen A har ikke en heltallig invers.", UserWarning)


array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])

## Numpy invers matrise 

Numpy kan regne ut inverse matriser for oss ved hjelp av funksjonen "solve" som vist under.

In [7]:
np.linalg.solve(A, np.eye(A.shape[0]))

array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])