## Beregning av invers matrise ved hjelp av python

Vi har allerede sett en python funksjon som kan gjøre Gauss Jordan eliminasjon. Denne funksjonen kan regne ut inverse matriser for oss.

In [1]:
import numpy as np

In [2]:
# importering av kode for gauss_jordan reduksjon
try:
    import python_linear_algebra as pla
except:
    !pip install python_linear_algebra@git+https://github.com/mbr085/python_linear_algebra
    import python_linear_algebra as pla
from python_linear_algebra.matrix_reduction import gauss_jordan, invers_matrise

Vi skriver matrisen fra før inn i python som en numpy array.

$$
AI = \left[\begin{array}{cccccc}
1 & 1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 0 & 1 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
$$


In [3]:
AI = np.array([
    [1, 1, 0, 1, 0, 0],
    [0, 2, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 1]
])

In [4]:
gauss_jordan(AI)

/home/mbr085/projects/V26MAT102/.venv/lib/python3.12/site-packages/python_linear_algebra/matrix_reduction.py:120: UserWarning: Den heltallige matrisen er ikke fullstendig redusert.
  warnings.warn("Den heltallige matrisen er ikke fullstendig redusert.", UserWarning)


array([[ 2,  0,  0,  2, -1,  0],
       [ 0,  2,  0,  0,  1,  0],
       [ 0,  0,  2,  0, -1,  2]])

Vi blir advart om at matrisen $AI$ ikke er blitt fullstendig redusert. Siste steg i reduksjonen deler radene på to, men etter å ha gjort det er ikke alle tallene i matrisen heltall lenger. 

Siden vi ga inn en matrise med heltall vil `gauss_jordan` gi tilbake en matrise med heltall.

Vi kan lese av den inverse matrisen til $A$ fra høyre halvden av matrisen vi fikk fra `gauss_jordan` ved å dele alle tallene på $2$..

## Funksjon som regner ut invers matrise

Vi leste av den inverse matrisen til en matrise $A$ fra Gauss Jordan eliminasjonen av $A$. I stedet for skrive av resultatet for hånd har jeg laget en 
python funksjon som finner den inverse matrisen for oss.

In [5]:
A = np.array([
    [1, 1, 0],
    [0, 2, 0],
    [0, 1, 1]
])

In [6]:
invers_matrise(A)

/home/mbr085/projects/V26MAT102/.venv/lib/python3.12/site-packages/python_linear_algebra/matrix_reduction.py:245: UserWarning: Matrisen A har ikke en heltallig invers.
  warnings.warn("Matrisen A har ikke en heltallig invers.", UserWarning)


array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])

Igjen blir vi advart om at matrisen vi ga inn i `invers_matrise` består av heltall, men det gjør resultatet ikke.

## Numpy invers matrise 

Numpy kan regne ut inverse matriser for oss ved hjelp av funksjonen "solve" som vist under.

In [7]:
np.linalg.solve(A, np.eye(A.shape[0]))

array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])