# Oppgaver i MAT102, uke 7

## Oppgave 1

1. Gjør oppgave 10.1.1 i MIP. Bruk gjerne python til det.
2. Gjør oppgave 10.1.2 i MIP. Bruk gjerne python til det hvis du vil.
3. Gjør oppgave 10.1.5 i MIP.

## Oppgave 2

Undersøk om følgende vektorer står vinkelrett på hverandre

1. $[3,1]$ og $[2, -6]$
2. $[1,2,3]$ og $[-3,2,-1]$
3. $[-1,-1,5]$ og $[3,-7,-1]$
4. $[\cos(t), \sin(t)]$ og $[\sin(t), -\cos(t)]$ for ukjent $t \in \mathbb{R}$ 

## Oppgave 3

Løs følgende oppgaver fra MIP for hånd eller ved hjelp av python:

1. 10.4.1, 10.4.2 og 10.4.5
2. 10.4.6
3. 10.5.1
4. 10.5.5

## Hint til oppgavene

Vinkelen $\theta$ mellom to vektorer $\vec a$ og $\vec b$ oppfylder $\vec a \cdot \vec b = \cos(\theta) \cdot |\vec a| \cdot |\vec b|$

En matrise kan skrives inn i python på denne måten

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,2,3,4,5,6],
    [7,8,9,1,2,3]
])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 1],
    [2, 3]
])

Vi kan vise matrisen ved å skrive navnet på den:

In [3]:
A

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

Produktet av matriser betegnes `@` i python:

In [4]:
C = A @ B
C

array([[107,  83],
       [107, 119]])

In [5]:
def normer_forste_element(vektor):
    """
    Normaliserer en vektor ved å dele alle elementer på det første ikke-null elementet.
    
    Parametere:
        vektor (np.ndarray): En 1D Numpy-array som skal normaliseres.
    
    Returnerer:
        np.ndarray: En normalisert vektor der det første ikke-null elementet er 1.
    """
    if np.allclose(vektor, 0):
        return vektor
    # Finn indeksen til det første elementet i vektoren som ikke er null
    forste_ikke_null_indeks = np.argmax(vektor != 0)
    
    # Hent verdien til det første ikke-null elementet
    forste_ikke_null_element = vektor[forste_ikke_null_indeks]
    
    # Returner den normaliserte vektoren
    return vektor / forste_ikke_null_element

def gauss_jordan(matrise, epsilon=1e-8):
    """
    Utfører Gauss-Jordan eliminasjon på en gitt matrise.
    
    Parametere:
        matrise (np.ndarray): En 2D Numpy-array som representerer matrisen.
        epsilon (float): En liten verdi for å håndtere numerisk presisjon.
    
    Returnerer:
        np.ndarray: En rekkeredusert matrise i redusert trappeform.
    """
    # Sett svært små verdier til null for å unngå numeriske feil
    matrise[np.abs(matrise) < epsilon] = 0
    
    # Hvis matrisen kun består av nuller, returner den uendret
    if np.allclose(matrise, 0):
        return matrise
    
    # Hvis matrisen har én rad, normaliser den første radens første ikke-null element
    elif len(matrise) == 1:
        matrise[0] = normer_forste_element(matrise[0])
        return matrise
    
    # Beregn radenes summer for å normalisere matrisen (gjør tallene mer håndterbare)
    rad_maksimummer = np.max(np.abs(matrise), axis=1)
    rad_maksimummer[rad_maksimummer <= epsilon] = 1
    matrise = matrise / rad_maksimummer[:, None]  # Normaliser hver rad
    # Finn kolonner som inneholder ikke-null elementer
    ikke_null_kolonner = np.any(matrise != 0, axis=0)
    
    # Finn indeksen til den første kolonnen med ikke-null elementer
    forste_ikke_null_kolonne = np.argmax(np.abs(ikke_null_kolonner))
    # Finn indeksen til raden med største verdi i den valgte kolonnen (pivot rad)
    pivot_rad_indeks = np.argmax(matrise[:, forste_ikke_null_kolonne])
    
    # Normaliser pivot-raden
    pivot_rad = normer_forste_element(matrise[pivot_rad_indeks])
    
    # Bytt plass på pivot-raden og den første raden
    matrise[pivot_rad_indeks] = matrise[0]
    matrise[0] = pivot_rad
    # Utfør eliminering for å gjøre alle elementene under pivoten null
    if matrise[0, forste_ikke_null_kolonne] > epsilon:
        matrise[1:] -= (matrise[1:, 0] / matrise[0, forste_ikke_null_kolonne])[:, None] * matrise[0]

    # Kall Gauss-Jordan rekursivt på den nedre delmatrisen
    matrise[1:, 1:] = gauss_jordan(matrise[1:, 1:])
    
    # Gjør den første raden null over pivot-posisjonene til de øvrige radene.
    for rad in matrise[1:]:
        if np.any(rad != 0):  # Hvis raden ikke er null
            # Finn indeksen til det første ikke-null elementet i raden
            forste_ikke_null_kolonne = np.argmax(rad != 0)
            
            # Trekk fra et multiplum av denne raden for å gjøre elementet over pivot null
            matrise[0] -= (matrise[0, forste_ikke_null_kolonne] / rad[forste_ikke_null_kolonne]) * rad
    
    # Returner den resulterende matrisen
    return matrise


Koden under reduserer matriser.

Her er et eksempel på bruk:

In [6]:
gauss_jordan(A)

array([[ 1. ,  0. , -1. , -5. , -6. , -7. ],
       [ 0. ,  1. ,  2. ,  4.5,  5.5,  6.5]])

In [7]:
gauss_jordan(B)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

La oss løse eksempel 2 på side 317 i MIP ved hjelp av koden over:

In [8]:
M = np.array([
    [2, 9, 0, 32, 13],
    [-1, 1, 6, 28, -19],
    [1, 2, -3, -7, 13]
])

In [9]:
gauss_jordan(M)

array([[ 1.,  0.,  0., 34.,  2.],
       [ 0.,  1.,  0., -4.,  1.],
       [ 0.,  0.,  1., 11., -3.]])

Vi ser at siste kolonne er for høyresiden av ligningen og at det er fire kolonner for ukjente variabler. Siden det er tre pivotkolonner er det tre bundne parametre og en fri parameter svarende til den nest siste kolonne som ikke er en pivotkolonne.