## Oppgave

La $f\colon \mathbb{R}^2 \to \mathbb{R}$ være funksjonen
$$f(\begin{bmatrix}x\\y\end{bmatrix}) = x^2 + 4y^2 -2x + 8y.$$ Vi vil
finne alle lokale minima for $f$ under betingelsen $x + 2y = 7$.

La $g\colon \mathbb{R}^2 \to \mathbb{R}$ være funksjonen
$g(\begin{bmatrix}x\\y\end{bmatrix})
  = x + 2y - 7$.

Finn $x, y$ og $\lambda$ slik at $\nabla f(\begin{bmatrix} x\\y \end{bmatrix}) = \lambda \nabla g(\begin{bmatrix} x\\y \end{bmatrix})$ og $g(\begin{bmatrix} x\\y \end{bmatrix}) = 0$

## Løsningsforslag

Gradientene til $f$ og $g$ er

$$\nabla f(\begin{bmatrix} x\\y \end{bmatrix}) = 
\begin{bmatrix}
2x - 2 \\
8y + 8
\end{bmatrix}$$
og
$$\nabla g(\begin{bmatrix} x\\y \end{bmatrix}) = 
\begin{bmatrix}
1 \\
2
\end{bmatrix}$$

Vi har ligningssystemet
$$0 = \nabla f(\begin{bmatrix} x\\y \end{bmatrix}) - \lambda \nabla g(\begin{bmatrix} x\\y \end{bmatrix}) = 
\begin{bmatrix}
2 & 0 & -1 \\
0 & 8 & -2
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
\lambda 
\end{bmatrix}
+
\begin{bmatrix}
-2 \\
8
\end{bmatrix},
$$
som også kan skrives
$$
\begin{bmatrix}
2 & 0 & -1 \\
0 & 8 & -2
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
\lambda 
\end{bmatrix}
=
\begin{bmatrix}
2 \\
-8
\end{bmatrix},
$$


Det vil si vi har de to ligningene
$$2x - \lambda = 2$$
og 
$$8y -2\lambda = -8.$$

Legger vi til en rad med ligningen $0 = x + 2y - 7$ får vi matrisen




$$
\begin{bmatrix}
2 & 0 & -1 \\
0 & 8 & -2 \\
1 & 2 & 0
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
\lambda 
\end{bmatrix}
 = 
\begin{bmatrix}
2 \\
-8\\
7
\end{bmatrix}
$$


Dette kan vi løse ved matrisereduksjon.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def f(x):
    x1, x2 = x
    return x1**2 + 4*x2**2 - 2*x1 + 8*x2
    

In [14]:
A = np.array([
    [2., 0, -1],
    [0, 8, -2],
    [1, 2, 0]
])
b = np.array([
    [2],
    [-8],
    [7]
])

In [ ]:
try:
    import python_linear_algebra
except:
    !pip install python_linear_algebra@git+https://github.com/mbr085/python_linear_algebra
    import python_linear_algebra

In [15]:
from python_linear_algebra.matrix_reduction import gauss_jordan

In [16]:
from python_linear_algebra.matrix_reduction import partikulaer_losning

In [17]:
B = gauss_jordan(np.hstack((A,b)))

In [18]:
B

array([[1., 0., 0., 5.],
       [0., 1., 0., 1.],
       [0., 0., 1., 8.]])

In [19]:
v = partikulaer_losning(A, b)
v

array([[5.],
       [1.],
       [8.]])

In [20]:
f(v[:-1])

array([27.])

In [21]:
v

array([[5.],
       [1.],
       [8.]])