# Gauss Jordan eliminasjon (MIP 10.4)

## Eksempel

Se på
$$
\begin{align}
2x + 3y  &= 5 \newline
4x + 5y &= 9
\end{align}
$$

Bemerk at følgende manipulasjoner ikke vil endre på løsningene til systemet
1. ta et tall gange den ene raden og leg til den andre raden
2. bytt om rader
3. gang en rad med et tall $\ne 0$

La os gjøre dette:

Trekk to ganger den første raden fra den andre raden og få:
$$
\begin{matrix}
2x & + & 3y  &=& 5 \newline
   &-& y &=& -1
\end{matrix}
$$

Legg nå tre ganger den andre raden til den første raden og få:
$$
\begin{matrix}
2x &  &   &=& 2 \newline
   &-& y &=& -1
\end{matrix}
$$

Gang til slutt første raden med en halv og andre raden med minus en:
$$
\begin{matrix}
x &  &   &=& 1 \newline
   && y &=& 1
\end{matrix}
$$

## Skjematisk form

Siden symbolene $x$ og $y$ hver gang står på samme posisjon i ligningssystemene kan vi la dem være innforståtte og skrive regningen over på skjematisk form:

$$
\left[\begin{array}{cc|c} 
   2 & 3 & 5  \\
   4 & 5 & 9 
\end{array}\right]
\sim
\left[\begin{array}{cc|c} 
   2 & 3 & 5  \\
   0 & -1 & -1 
\end{array}\right]
\begin{array}{c} 
     \\
   \mathrm{II} - 2 \mathrm{I}
\end{array}
\sim
\left[\begin{array}{cc|c} 
   2 & 0 & 2  \\
   0 & -1 & -1 
\end{array}\right]
\begin{array}{c}
\mathrm{I} + 3\mathrm{II} \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{cc|c} 
   1 & 0 & 1  \\
   0 & 1 & 1 
\end{array}\right]
\begin{array}{c}
\frac 12 \cdot \mathrm{I} \newline
- \mathrm{II}
\end{array}
$$

Dette kan leses av som
$$
\begin{array}{ccccc} 
   x & + & 0 & = & 1  \\
   0 & + & y & = & 1 
\end{array}
$$

### Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    4x_0 &+& x_1 & + &4x_2 &+ &x_3& + &5x_4 &= &3
\end{array}
$$

Som over kan vi "redusere" systemet på skjematisk form:

$$
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  4 & 1 & 4 & 1 & 5 & 3
\end{array}
\right]
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & -1/3 & 0 & -1/3 & -1/3 & 1/3
\end{array}
\right]
\begin{array}{c}
\\
\mathrm{II} - 4\mathrm{I}/3
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & 1 & 0 & 1 & 1 & -1
\end{array}
\right]
\begin{array}{c}
\\
-3\mathrm{II}
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  3 & 0 & 3 & 0 & 3 & 3 \\
  0 & 1 & 0 & 1 & 1 & -1 
\end{array}
\right]
\begin{array}{c}
\mathrm{I} -
\mathrm{II}\\
\phantom{ }
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  1 & 0 & 1 & 0 & 1 & 1 \\
  0 & 1 & 0 & 1 & 1 & -1 
\end{array}
\right]
\begin{array}{c}
\mathrm{I}/3
\\
\phantom{ }
\end{array}
$$

Setter vi inn de ukjente fås det ekvivalente systemet:
$$
\begin{array}{ccccccccccc}
    x_0 &+& & & x_2& +& &&x_4& = &1 \\
     && x_1 & + & & &x_3& + &x_4 &= &-1
\end{array}
$$

Her er det uendelig mange løsninger. Uansett verdiene $x_2$, $x_3$ og $x_4$ får vi en løsning ved å sette $x_0 = 1 - x_2 - x_4$ og $x_1 = -1 - x_3 - x_4$.

## Målet med Gauss Jordan eliminasjon

På første rad vil vi ha et ettall så langt til venstre som mulig og nuller under det. Deretter vil vi på andre rad ha et ettall så langt til venstre som mulig og nuller under og over det. Sådan fortsettes med resten av radene. 

I praksis er det enklere å ikke gjøre tallene over de utvalgte ettallene lik null underveis. For å løse ligningssystemet trenger vi ikke disse nullene, men når nullene er der er det enklere å lese av løsninger.

## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &1
\end{array}
$$

Vi ser umiddelbart at dette ikke kan gå bra siden det er umulig å ha $2 = 1$.

La oss likevel se hva som skjer når vi prøver å "redusere" dette systemet på skjematisk form:

$$
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  3 & 1 & 3 & 1 & 4 & 1 
\end{array}
\right]
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & 0 & 0 & 0 & 0 & -1
\end{array}
\right]
\begin{array}{c}
\\
\mathrm{II} - \mathrm{I}
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  1 & 1/3 & 1 & 1/3 & 4/3 & 2/3 \\
  0 & 0 & 0 & 0 & 0 & -1
\end{array}
\right]
\begin{array}{c}
\mathrm{I} / 3
\\
\phantom{ }
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  1 & 1/3 & 1 & 1/3 & 4/3 & 2/3 \\
  0 & 0 & 0 & 0 & 0 & 1
\end{array}
\right]
\begin{array}{c}
\phantom{}
\\
-\mathrm{II}
\end{array}
$$

Her er vi kommet frem til at hvis ligningssystemet har en løsning da er $0 = -1$. Siden det ikke er riktig har systemet ingen løsning!

## Python kode

In [1]:
try:
    import python_linear_algebra
except:
    !pip install python_linear_algebra@git+https://github.com/mbr085/python_linear_algebra
    import python_linear_algebra

In [2]:
from python_linear_algebra.matrix_reduction import gauss_jordan, partikulaer_losning, null_rom

In [3]:
import numpy as np

In [4]:
# La oss bruke python kode på denne matrisen

A = np.array([
    [3, 1, 3, 1, 4, 2],    
    [3, 1, 3, 1, 4, 1]
])

gauss_jordan(A)

array([[3, 1, 3, 1, 4, 0],
       [0, 0, 0, 0, 0, 1]])

## Eksempel

Se på
$$
\begin{align}
2x + 3y  &= 5 \newline
4x + 5y &= 9
\end{align}
$$

Vi kan løse dette med koden vår slik som dette:

In [5]:
A = np.array([
    [2, 3],
    [4, 5]
])

b = np.array([5, 9])

In [6]:
x = partikulaer_losning(A, b)

In [7]:
A @ x

array([[5.],
       [9.]])

In [8]:
x

array([[1.],
       [1.]])

For å vite hvor mange løsninger det finnes kan vi se på nullrommet

In [9]:
null_rom(A)

[]

Dette betyr at nullvektoren $0$ er eneste vektor $\vec v$ med $A \cdot \vec v = 0$ 

## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccc}
    1x_0 &+& 2x_1& +& 3x_2& = &2 \\
    4x_0 &+& 5x_1& +& 6x_2& = &5 \\
    7x_0 &+& 8x_1& +& 9x_2& = &8 
\end{array}
$$


Gauss Jordan reduksjon blir

$$
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    4 & 5 & 6 & 5 \\
    7 & 8 & 9 & 8
\end{array}
\right]
\sim
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    0 & -3 & -6 & -3 \\
    0 & -6 & -12 & -6
\end{array}
\right]
\begin{array}{c}
    \\
    \mathrm{II} - 4\mathrm{I} \\
    \mathrm{III} - 7\mathrm{I} 
\end{array}
\sim
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    0 & 1 & 2 & 1 \\
    0 & 0 & 0 & 0
\end{array}
\right]
\begin{array}{c}
    \\
    -\mathrm{II}/3\\
    \mathrm{III} - 2\mathrm{II} 
\end{array}
\sim
\left[
\begin{array}{ccc|c}
    1 & 0 & -1 & 0 \\
    0 & 1 & 2 & 1 \\
    0 & 0 & 0 & 0
\end{array}
\right]
\begin{array}{c}
    \mathrm{I} - 2\mathrm{II}\\ 
    \phantom{A}\\
    \phantom{A}
\end{array}
$$

Her leser vi av
$$
\begin{array}{cccccccc}
    x_0 &-& & & x_2& = &0 \\
     && x_1& +& 2x_2& = &1 \\
    &&&&0& = &0 
\end{array}
$$

Uansett verdien til $x_2$ har vi en løsning der $x_0 = x_2$ og $x_1 = 1 - 2x_2$.

Det vil si løsningene vi har funnet er på formen
Det ligner ikke på løsningen vi fant for hånd over:

$$
\left[\begin{array}{c}
0 \\ 1 \\ 0 \end{array}\right]
+
x_2
\left[\begin{array}{c}
1 \\ -2 \\ 1 \end{array}\right]
=
\left[\begin{array}{c}
x_2 \\ 1 - 2x_2 \\ x_2 \end{array}\right]
$$

for en $x_2$.

Her skriver vi igjen inn koeffisientmatrisen og høyresiden:

In [10]:
import numpy as np

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([2, 5, 8])

In [12]:
x = partikulaer_losning(A, b)

In [13]:
x

array([[0.5],
       [0. ],
       [0.5]])

In [14]:
A @ x

array([[2.],
       [5.],
       [8.]])

In [15]:
null_rom_for_A = null_rom(A)

In [16]:
null_rom_for_A

[array([[-1],
        [ 2],
        [-1]])]

Vi ser at det er en vektor $\vec v$ forskjellig fra nullvektoren slik at $A \cdot \vec v = 0$

In [17]:
v = null_rom_for_A[0]
v

array([[-1],
       [ 2],
       [-1]])

In [18]:
A @ v

array([[0],
       [0],
       [0]])

Siden $A \cdot \vec v = \vec 0$ har vi $A \cdot(\vec x + x_2 \vec v) = A \cdot \vec x + x_2 A \cdot \vec v = A \cdot \vec x
+ x_2 \vec 0 = A \cdot \vec x = \vec b$. 

Setter vi inn den $\vec x$ vi fant over med $A \cdot \vec x = \vec 0$ får vi

$$\vec x + x_2 \vec v =
\left[\begin{array}{c}
0.5 \\ 0 \\ 0.5 \end{array}\right]
+
x_2
\left[\begin{array}{c}
-1 \\ 2 \\ -1 \end{array}\right]
=
\left[\begin{array}{c}
0.5 - x_2 \\ 2x_2 \\ 0.5 - x_2 \end{array}\right]
$$

Det ligner ikke på løsningen vi fant for hånd over:

$$\vec x + x_2 \vec v =
\left[\begin{array}{c}
0 \\ 1 \\ 0 \end{array}\right]
+
x_2
\left[\begin{array}{c}
1 \\ -2 \\ 1 \end{array}\right]
=
\left[\begin{array}{c}
x_2 \\ 1 - 2x_2 \\ x_2 \end{array}\right]
$$

## Oppgave:

Avgjør om dette er de samme løsningene som vi fant for hånd.

## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &1
\end{array}
$$

In [19]:
A = np.array([
    [3., 1, 3, 1, 4],
    [3, 1, 3, 1, 4],
])

b = np.array([2., 1])

In [20]:
partikulaer_losning(A, b)

Det finnes ingen løsning til det lineære ligningssystemet


array([[-0.],
       [-0.],
       [-0.],
       [-0.],
       [-0.]])

Pass på!. **Det finnes ingen løsning!** 

Vektoren som kom ut er ikke en løsning.