In [1]:
import numpy as np

In [131]:
def normer_forste_element(a):
    forste_ikke_null_element_indeks = np.argmax(a != 0)
    forste_ikke_null_element = a[forste_ikke_null_element_indeks]
    return a / forste_ikke_null_element
    
def gauss_jordan(A):
    if np.all(A == 0):
        return A
    elif len(A) == 1:
        A[0] = normer_forste_element(A[0])
        return A
    else:
        rad_summer = np.sum(A, axis=1)
        A = A / rad_summer[:, None]
        ikke_null_kolonner = np.any(A != 0, axis=0)
        forste_ikke_null_kolonne_indeks = np.argmax(ikke_null_kolonner)
        pivot_rad_indeks = np.argmax(A[:, forste_ikke_null_kolonne_indeks])
        pivot_rad = normer_forste_element(A[pivot_rad_indeks])
        A[pivot_rad_indeks] = A[0]
        A[0] = pivot_rad
        A[1:] = A[1:] - (A[1:, 0] / A[0, 0]) * A[0]
        A[1:, 1:] = gauss_jordan(A[1:, 1:])
        for rad in A[1:]:
            if np.any(rad != 0):
                forste_ikke_null_element_indeks = np.argmax(rad != 0)
                A[0] = A[0] - (A[0, forste_ikke_null_element_indeks] / rad[forste_ikke_null_element_indeks]) * rad
    return A

In [132]:
A = (1 + np.arange(6)).reshape((2,3))

In [133]:
gauss_jordan(A)

array([[ 1.,  0., -1.],
       [ 0.,  1.,  2.]])

In [139]:
def normer_forste_element(a):
    # Finn indeksen til det første elementet som ikke er null
    forste_ikke_null_element_indeks = np.argmax(a != 0)
    
    # Hent verdien til det første ikke-null elementet
    forste_ikke_null_element = a[forste_ikke_null_element_indeks]
    
    # Returner den normaliserte vektoren, der alle elementer er delt på det første ikke-null elementet
    return a / forste_ikke_null_element
    
def gauss_jordan(A):
    # Hvis matrisen kun består av nuller, returner den uendret
    if np.all(A == 0):
        return A
    
    # Hvis matrisen har én rad, normaliser den første radens første ikke-null element
    elif len(A) == 1:
        A[0] = normer_forste_element(A[0])
        return A
    else:
        # Beregn radens summene for å normalisere matrisen
        # rad_summer = np.sum(A, axis=1)
        # A = A / rad_summer[:, None]  # Normaliser hver rad ved å dele med radens sum
        
        # Finn kolonner som inneholder ikke-null elementer
        ikke_null_kolonner = np.any(A != 0, axis=0)
        
        # Finn indeksen til den første kolonnen med ikke-null elementer
        forste_ikke_null_kolonne_indeks = np.argmax(ikke_null_kolonner)
        
        # Finn indeksen til raden med største verdi i den valgte kolonnen (pivot rad)
        pivot_rad_indeks = np.argmax(A[:, forste_ikke_null_kolonne_indeks])
        
        # Normaliser pivot raden
        pivot_rad = normer_forste_element(A[pivot_rad_indeks])
        
        # Bytt plass på pivot raden og den første raden
        A[pivot_rad_indeks] = A[0]
        A[0] = pivot_rad
        
        # Utfør eliminering for å gjøre alle elementene under pivoten null
        A[1:] = A[1:] - (A[1:, 0] / A[0, 0]) * A[0]
        
        # Kall gauss_jordan rekursivt på den nedre delmatrisen
        A[1:, 1:] = gauss_jordan(A[1:, 1:])
        
        # Gjør de andre radene null i forhold til den første raden
        for rad in A[1:]:
            if np.any(rad != 0):  # Hvis raden ikke er null
                # Finn indeksen til det første ikke-null elementet i raden
                forste_ikke_null_element_indeks = np.argmax(rad != 0)
                
                # Utfør radeligning for å gjøre første element i den første raden null
                A[0] = A[0] - (A[0, forste_ikke_null_element_indeks] / rad[forste_ikke_null_element_indeks]) * rad
    
    # Returner den resulterende matrisen
    return A


In [140]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
normer_forste_element(A[1])

array([1.  , 1.25, 1.5 ])

In [142]:
np.any(A != 0, axis=0)

array([ True,  True,  True])

In [143]:
gauss_jordan(A)

array([[ 1,  0, -1],
       [ 0,  1,  2]])

In [50]:
ikke_null_kolonner = np.any(A != 0, axis=0)
forste_ikke_null_kolonne_indeks = np.argmax(ikke_null_kolonner)

In [51]:
pivot_rad_indeks = np.argmax(A[:, forste_ikke_null_kolonne_indeks])

In [52]:
pivot_rad_indeks

np.int64(1)

In [47]:
A[:, ikke_null_kolonner]

array([[0, 1, 2],
       [3, 4, 5]])