In [1]:
import numpy as np

In [2]:
P = np.array([
    [1, 2, 0, 0],
    [1, 1, 0, 0],
    [1, 1, 1, 1],
    [0, 0, 1, 2]
])

In [3]:
D = np.diag([1, 2, 3, 4])

In [5]:
A = P @ D @ np.linalg.inv(P)

In [10]:
(A@P).astype(int)

array([[1, 4, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 4],
       [0, 0, 3, 8]])

In [8]:
P@D

array([[1, 4, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 4],
       [0, 0, 3, 8]])

In [11]:
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
import array_to_latex as a2l

In [ ]:
a2l.to_ltx(P, frmt = '{:6.2f}', arraytype = 'array')

In [ ]:
a2l.to_ltx(P, frmt = '{0:d}', arraytype = 'array')

In [ ]:
B = P @ D @ np.linalg.inv(P) - 2*np.eye(4)

In [ ]:
B

In [ ]:
a2l.to_ltx(B.astype(int), frmt = '{0:d}', arraytype = 'array')

In [ ]:
a2l.to_ltx(P @ D @ np.linalg.inv(P).astype(int), frmt = '{0:d}', arraytype = 'array')

In [ ]:
a2l.to_ltx(D.astype(int), frmt = '{0:d}', arraytype = 'array')

In [17]:
P = np.array([
    [1, 2, 3],
    [0, 1, 2],
    [1, 0, 1]
])

In [18]:
D = np.diag([1, 2, 3])

In [19]:
A = P @ D @ np.linalg.inv(P)

In [20]:
A

array([[ 0.,  4.,  1.],
       [-1.,  4.,  1.],
       [-1.,  2.,  2.]])

In [24]:
a2l.to_ltx(A.astype(int), frmt = '{0:d}', arraytype = 'bmatrix')

\begin{bmatrix}
  0  &  4  &  1 \\
 -1  &  4  &  1 \\
 -1  &  2  &  2 
\end{bmatrix}


In [25]:
A@P

array([[1., 4., 9.],
       [0., 2., 6.],
       [1., 0., 3.]])

In [26]:
P @D

array([[1, 4, 9],
       [0, 2, 6],
       [1, 0, 3]])

In [27]:
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
A

array([[ 0.,  4.,  1.],
       [-1.,  4.,  1.],
       [-1.,  2.,  2.]])

In [30]:
np.linalg.det(A - 2*np.eye(3))

np.float64(0.0)