# To utvalgs t-test

# Oppgave

En butikkjede måler effekten av plassering av godteri i butikkene. 

Femti tilfeldig utvalgte butikker (z-butikkene) plasserer godteriet ved inngangen til butikken.

Femti tilfeldig utvalgte butikker (y-butikkene) beholdt godteriet i standard plasseringen rett før kassene.

Vi vil teste hypotesen om salget av godteri falt ved å flytte på plasseringen til godteriet.

Vi gjør nullhypotesen at salget ikke endret seg med den alternative hypotesen at salget av godteri falt ved å endre plassering:

**Antatte gjennomsnittsverdier** $\mu_y$ og $\mu_z$

**Nullhypotese ($H_0)$:** $\mu_y = \mu_z$.

**Alternativ hypotese ($H_a$):** $\mu_y > \mu_z$.

Salget av godteri i butikkene i prøveperioden i KNOK, det til si i tusinder av kroner, fordelte seg slik:


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

In [72]:
rng = np.random.default_rng(seed=0)

In [73]:
y = rng.normal(loc = 44, scale=9, size=50)

In [74]:
y = np.round(y).astype(int)

In [75]:
z = rng.normal(loc = 40, scale=9, size=50)

In [76]:
z = np.round(z).astype(int)

In [77]:
y

array([45, 43, 50, 45, 39, 47, 56, 53, 38, 33, 38, 44, 23, 42, 33, 37, 39,
       41, 48, 53, 43, 56, 38, 47, 52, 45, 37, 36, 40, 46, 35, 42, 43, 49,
       46, 47, 38, 43, 51, 57, 33, 58, 56, 51, 46, 41, 57, 62, 60, 56])

In [78]:
f'{y}'

'[45 43 50 45 39 47 56 53 38 33 38 44 23 42 33 37 39 41 48 53 43 56 38 47\n 52 45 37 36 40 46 35 42 43 49 46 47 38 43 51 57 33 58 56 51 46 41 57 62\n 60 56]'

In [79]:
z

array([43, 29, 40, 46, 28, 44, 44, 46, 29, 34, 36, 29, 56, 36, 43, 38, 54,
       52, 46, 20, 40, 46, 49, 34, 56, 28, 34, 48, 40, 58, 42, 34, 37, 30,
       29, 46, 45, 52, 33, 55, 37, 54, 36, 33, 42, 49, 41, 35, 28, 27])

In [80]:
np.mean(y), np.std(y)

(np.float64(45.16), np.float64(8.18867510651143))

In [81]:
np.sqrt(np.mean(y**2) - np.mean(y)**2)

np.float64(8.188675106511445)

In [82]:
np.mean(y**2)

np.float64(2106.48)

In [83]:
' '.join((f'gjennomsnittet til y-verdiene er {np.mean(y)}',
        f'og gjennomsnittet til kvadratet på y-verdiene er {np.mean(y**2)}'))

'gjennomsnittet til y-verdiene er 45.16 og gjennomsnittet til kvadratet på y-verdiene er 2106.48'

In [123]:
' '.join((f'Gjennomsnittet til z-verdiene er {np.mean(z):.0f}',
        f'og gjennomsnittet til kvadratet på z-verdiene er {np.mean(z**2):.0f}'))

'Gjennomsnittet til z-verdiene er 40 og gjennomsnittet til kvadratet på z-verdiene er 1701'

$t$-verdien for en to utvalgs test er:

$$t = \frac{E(y) - E(z)}{\sigma(y, z) \sqrt{2/n}}.$$

Her er $E(y)$ gjennomsnittet til $y$-verdiene og $\sigma(y, z)$ er det kombinerte standardavviket
$$\sigma(y,z) = \sqrt{\frac{\sigma(y)^2 + \sigma(z)^2}{2}}.$$

Husk gjerne at standardavviket $\sigma(y)$ kan beregnes ved formelen $\sigma(y)^2 = E(y^2) - E(y)^2$.

## Vil teste:
**Antatte gjennomsnittsverdier** $\mu_y$ og $\mu_z$

**Nullhypotese ($H_0)$:** $\mu_y = \mu_z$.

**Alternativ hypotese ($H_a$):** $\mu_y > \mu_z$.

In [84]:
Ey = np.mean(y)
Ey2 = np.mean(y**2)
Ez = np.mean(z)
Ez2 = np.mean(z**2)

In [85]:
sy = np.sqrt(Ey2 - Ey**2)
sz = np.sqrt(Ez2 - Ez**2)

In [86]:
sy, sz

(np.float64(8.188675106511445), np.float64(9.111070189610015))

In [87]:
syz = np.sqrt((Ey2 - Ey**2 + Ez2 - Ez**2)/2)

In [88]:
syz

np.float64(8.662159084200674)

In [91]:
t = (Ey - Ez)/(np.sqrt(2/len(y)) * syz)

In [92]:
Ey, Ez

(np.float64(45.16), np.float64(40.22))

## Spørsmål

Kan vi forkaste nullhypotesen med et konfidensnivå på fem prosent?

## To utvalgs t-test

La $n$ være antallet av observasjoner i hver av utvalgene. For oss er $n = 50$.

La $E(y)$ være gjennomsnittet til tallene $y_i$ og la $E(z)$ være gjennomsnittet til tallene $z_i$. 

Vi kommer igjen til å gi en formel for en $t$-verdi som du for eksempel [finner på Wikipedia sin side om t-test i avsnittet "**Equal sample sizes and variance**".](https://en.wikipedia.org/wiki/Student's_t-test)

For å skrive formelen litt fint vil jeg innføre det kombinerte standardavviket
$$\sigma(y,z) = \sqrt{\frac{\sigma(y)^2 + \sigma(z)^2}{2}}.$$

Husk gjerne at standardavviket $\sigma(y)$ er gitt ved formelen $\sigma(y)^2 = E(y^2) - E(y)^2$.

$t$-verdien for vår to utvalgs test er:

$$t = \frac{E(y) - E(z)}{\sigma(y, z) \sqrt{2/n}}.$$

Antallet av frihetsgrader er $2n - 2$.

## Spesifikk oppgave:

Gitt formelen for $t$-verdi over, finn $t$-verdien og $p$-verdien for nullhypotesen.

[Hint](toutvalghint.ipynb)

In [93]:
antall_frihetsgrader = 2*len(y) - 2

In [95]:
p_verdi = 1 - scipy.stats.t.cdf(t, df=antall_frihetsgrader)

In [96]:
p_verdi

np.float64(0.0026535105463975084)

In [97]:
t

np.float64(2.8514830725115057)

In [101]:
tt = np.linspace(0, 3, 10)

In [103]:
pp = 1 - scipy.stats.t.cdf(tt, df=antall_frihetsgrader)

In [109]:
np.round(np.vstack((tt, pp)), 3)

array([[0.000e+00, 3.330e-01, 6.670e-01, 1.000e+00, 1.333e+00, 1.667e+00,
        2.000e+00, 2.333e+00, 2.667e+00, 3.000e+00],
       [5.000e-01, 3.700e-01, 2.530e-01, 1.600e-01, 9.300e-02, 4.900e-02,
        2.400e-02, 1.100e-02, 4.000e-03, 2.000e-03]])

In [110]:
import array_to_latex

In [113]:
array_to_latex.to_ltx(np.vstack((tt, pp)), frmt='{:1.3f}', arraytype='array')

\begin{array}{ c, c, c, c, c, c, c, c, c, c}
  0.000 &  0.333 &  0.667 &  1.000 &  1.333 &  1.667 &  2.000 &  2.333 &  2.667 &  3.000\\
  0.500 &  0.370 &  0.253 &  0.160 &  0.093 &  0.049 &  0.024 &  0.011 &  0.004 &  0.002
\end{array}


\begin{array}{l | c, c, c, c, c, c, c, c, c, c}
  t & 0.000 &  0.333 &  0.667 &  1.000 &  1.333 &  1.667 &  2.000 &  2.333 &  2.667 &  3.000\\
  \hline
  p & 0.500 &  0.370 &  0.253 &  0.160 &  0.093 &  0.049 &  0.024 &  0.011 &  0.004 &  0.002
\end{array}


In [124]:
np.std(z)

np.float64(9.11107018961)

In [125]:
sz

np.float64(9.111070189610015)

In [126]:
syz

np.float64(8.662159084200674)

In [127]:
t

np.float64(2.8514830725115057)